name: issue-workflow 1
on:
  issues:
    types: [opened]

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hellow world
        echo githut action
