name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stage
        - prod
jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hellow world
        echo githut action
    - name: echo input
      run: |
        echo ${{ inputs.name }}
        echo ${{ inputs.environment }}
