name: needs
on: push

jobs:
  push-job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
  push-job2:
    runs-on: ubuntu-latest
    needs: [push-job1]
    steps:
    - name: step2
      run: echo hello world2
  push-job3:
    runs-on: ubuntu-latest
    steps:
    - name: step3
      run: |
        echo "job3 failed"
        exit 1
  push-job4:
    runs-on: ubuntu-latest
    needs: [push-job3]
    steps:
    - name: step4
      run: echo "job4 done"


